<script setup lang="ts">
import{onMounted,ref}from'vue';import AppButton from'./ui/AppButton.vue';import AppInput from'./ui/AppInput.vue';import{apiRequest,setPinToken}from'../services/api';
interface GateSettings{version:number;pinEnabled:boolean;onboardingCompleted:boolean;userNickname:string|null}
const emit=defineEmits<{unlocked:[]}>(),pin=ref(''),loading=ref(true),error=ref(''),mode=ref<'pin'|'onboarding'>('pin'),settings=ref<GateSettings|null>(null),nickname=ref(''),dinerName=ref('我');
async function initialize(){try{settings.value=await apiRequest<GateSettings>('/settings');if(!settings.value.onboardingCompleted){mode.value='onboarding';nickname.value=settings.value.userNickname??'';return}if(!settings.value.pinEnabled){emit('unlocked');return}try{await apiRequest('/settings/pin/session');emit('unlocked');return}catch{setPinToken(null)}}catch(e){error.value=e instanceof Error?e.message:'无法读取本地设置'}finally{loading.value=false}}
async function completeOnboarding(){if(!settings.value||!nickname.value.trim()||!dinerName.value.trim()){error.value='请填写昵称和默认食用者';return}loading.value=true;error.value='';try{settings.value=await apiRequest<GateSettings>('/settings/onboarding',{method:'POST',body:JSON.stringify({version:settings.value.version,nickname:nickname.value.trim(),dinerName:dinerName.value.trim(),pin:pin.value||null})});if(pin.value){const result=await apiRequest<{valid:boolean;token:string|null}>('/settings/pin/verify',{method:'POST',body:JSON.stringify({pin:pin.value})});setPinToken(result.token)}emit('unlocked')}catch(e){error.value=e instanceof Error?e.message:'首次设置失败'}finally{loading.value=false}}
async function unlock(){loading.value=true;error.value='';try{const result=await apiRequest<{valid:boolean;token:string|null}>('/settings/pin/verify',{method:'POST',body:JSON.stringify({pin:pin.value})});if(!result.valid||!result.token){error.value='PIN 不正确';return}setPinToken(result.token);emit('unlocked')}catch(e){error.value=e instanceof Error?e.message:'验证失败'}finally{loading.value=false}}
onMounted(initialize);
</script>
<template><main class="pin-gate"><section v-if="mode==='onboarding'" class="app-card"><p class="business-eyebrow">First setup</p><h1>欢迎来到搭饭小馆</h1><p>先完成一次本地设置。所有内容只保存在这台电脑的 SQLite 数据库中。</p><AppInput v-model="nickname" label="你的昵称"/><AppInput v-model="dinerName" label="默认食用者"/><AppInput v-model="pin" type="password" label="访问 PIN（可选，4–8 位数字）"/><p v-if="error" class="pin-error">{{error}}</p><AppButton :loading="loading" @click="completeOnboarding">完成设置并进入</AppButton></section><section v-else class="app-card"><p class="business-eyebrow">Local access</p><h1>欢迎回到搭饭小馆</h1><p>请输入本地 PIN 后继续。PIN 只在这台服务所在的本地数据库中验证。</p><AppInput v-model="pin" type="password" label="PIN" error="" @keyup.enter="unlock"/><p v-if="error" class="pin-error">{{error}}</p><AppButton :loading="loading" @click="unlock">进入小馆</AppButton></section></main></template>
<style scoped>.pin-gate{min-height:100vh;display:grid;place-items:center;padding:20px;background:var(--color-page-bg)}.pin-gate section{display:grid;gap:16px;width:min(100%,420px)}.pin-gate h1,.pin-gate p{margin:0}.pin-error{color:var(--color-danger)}</style>
