import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';import type { PrismaClient } from '@prisma/client';import QRCode from 'qrcode';import { VersionConflictError } from '../../database/optimistic-lock.js';
const pinSessions=new Map<string,number>();const sessionLifetime=12*60*60*1000;
const publicSettings=(s:{pinHash:string|null}&Record<string,unknown>)=>{const{pinHash:_,...rest}=s;return rest};
export async function getSettings(db:PrismaClient){const value=await db.settings.upsert({where:{id:1},create:{id:1},update:{}});return publicSettings(value)}
async function assertVersion(db:PrismaClient,version:number){const current=await db.settings.upsert({where:{id:1},create:{id:1},update:{}});if(current.version!==version)throw new VersionConflictError({entity:'Settings',id:'1',expectedVersion:version,actualVersion:current.version});return current}
export async function updateSettings(db:PrismaClient,version:number,input:{appName?:string;subtitle?:string;userNickname?:string|null;userAvatarPath?:string|null;defaultPort?:number;autoBackupEnabled?:boolean;autoDeductInventory?:boolean;defaultRepeatDays?:number;onboardingCompleted?:boolean}){await assertVersion(db,version);if(input.defaultPort!=null&&(!Number.isInteger(input.defaultPort)||input.defaultPort<1024||input.defaultPort>65535))throw Object.assign(new Error('端口必须在 1024 到 65535 之间'),{statusCode:400});const value=await db.settings.update({where:{id:1},data:{...input,version:{increment:1}}});return publicSettings(value)}
const hashPin=(pin:string)=>{const salt=randomBytes(16).toString('hex');return`${salt}:${scryptSync(pin,salt,32).toString('hex')}`};
export async function completeOnboarding(db:PrismaClient,input:{version:number;nickname:string;dinerName:string;pin?:string|null}){const nickname=input.nickname?.trim(),dinerName=input.dinerName?.trim();if(!nickname||!dinerName)throw Object.assign(new Error('昵称和默认食用者不能为空'),{statusCode:400});if(input.pin&&!/^\d{4,8}$/.test(input.pin))throw Object.assign(new Error('PIN 必须是 4 到 8 位数字'),{statusCode:400});pinSessions.clear();return db.$transaction(async tx=>{const current=await tx.settings.upsert({where:{id:1},create:{id:1},update:{}});if(current.version!==input.version)throw new VersionConflictError({entity:'Settings',id:'1',expectedVersion:input.version,actualVersion:current.version});const existing=await tx.diner.findFirst({where:{name:dinerName}});if(!existing)await tx.diner.create({data:{name:dinerName,active:true}});else if(!existing.active)await tx.diner.update({where:{id:existing.id},data:{active:true,version:{increment:1}}});const value=await tx.settings.update({where:{id:1},data:{userNickname:nickname,onboardingCompleted:true,pinEnabled:Boolean(input.pin),pinHash:input.pin?hashPin(input.pin):null,version:{increment:1}}});return publicSettings(value)})}
export async function setPin(db:PrismaClient,version:number,pin:string|null,enabled:boolean){pinSessions.clear();await assertVersion(db,version);if(enabled&&!/^\d{4,8}$/.test(pin??''))throw Object.assign(new Error('PIN 必须是 4 到 8 位数字'),{statusCode:400});const value=await db.settings.update({where:{id:1},data:{pinEnabled:enabled,pinHash:enabled?hashPin(pin!):null,version:{increment:1}}});return publicSettings(value)}
export async function verifyPin(db:PrismaClient,pin:string){const value=await db.settings.upsert({where:{id:1},create:{id:1},update:{}});if(!value.pinEnabled)return{valid:true,required:false};if(!value.pinHash)return{valid:false,required:true};const[salt,expected]=value.pinHash.split(':');const actual=scryptSync(pin,salt!,32);const target=Buffer.from(expected!,'hex');return{valid:actual.length===target.length&&timingSafeEqual(actual,target),required:true}}
export async function verifyPinAndCreateSession(db:PrismaClient,pin:string){const result=await verifyPin(db,pin);if(!result.valid)return{...result,token:null};const token=randomBytes(32).toString('hex');pinSessions.set(token,Date.now()+sessionLifetime);return{...result,token}}
export function validPinSession(token:string|undefined){if(!token)return false;const expires=pinSessions.get(token);if(!expires||expires<Date.now()){if(expires)pinSessions.delete(token);return false}return true}
export function clearPinSessions(){pinSessions.clear()}
export async function createAccessQr(url:string){if(!/^https?:\/\/[\w.:[\]-]+(?:\/.*)?$/.test(url))throw Object.assign(new Error('局域网访问地址无效'),{statusCode:400});return{url,dataUrl:await QRCode.toDataURL(url,{width:320,margin:2,color:{dark:'#2f282b',light:'#fff8fa'}})}}
