<script setup lang="ts">
import { onMounted, ref } from 'vue';import AppButton from '../components/ui/AppButton.vue';import AppErrorState from '../components/ui/AppErrorState.vue';import AppInput from '../components/ui/AppInput.vue';import {apiRequest,ApiRequestError,setPinToken} from '../services/api';
interface Settings{id:number;appName:string;subtitle:string;userNickname:string;defaultPort:number;autoBackupEnabled:boolean;autoDeductInventory:boolean;defaultRepeatDays:number;onboardingCompleted:boolean;pinEnabled:boolean;version:number}
const data=ref<Settings|null>(null),loading=ref(true),saving=ref(false),error=ref(''),message=ref(''),pin=ref(''),qr=ref('');
async function load(){loading.value=true;try{const value=await apiRequest<Settings&{userNickname:string|null}>('/settings');data.value={...value,userNickname:value.userNickname??''}}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
async function save(){if(!data.value)return;saving.value=true;try{data.value=await apiRequest('/settings',{method:'PUT',body:JSON.stringify({version:data.value.version,appName:data.value.appName,subtitle:data.value.subtitle,userNickname:data.value.userNickname,defaultPort:Number(data.value.defaultPort),autoBackupEnabled:data.value.autoBackupEnabled,autoDeductInventory:data.value.autoDeductInventory,defaultRepeatDays:Number(data.value.defaultRepeatDays),onboardingCompleted:true})});message.value='设置已保存'}catch(e){handle(e)}finally{saving.value=false}}
async function savePin(enabled:boolean){if(!data.value)return;try{const nextPin=pin.value;data.value=await apiRequest('/settings/pin',{method:'PUT',body:JSON.stringify({version:data.value.version,pin:enabled?nextPin:null,enabled})});if(enabled){const session=await apiRequest<{valid:boolean;token:string|null}>('/settings/pin/verify',{method:'POST',body:JSON.stringify({pin:nextPin})});setPinToken(session.token)}else setPinToken(null);pin.value='';message.value=enabled?'PIN 已启用':'PIN 已关闭'}catch(e){handle(e)}}
async function makeQr(){try{const result=await apiRequest<{dataUrl:string}>('/settings/access-qr',{query:{url:location.origin}});qr.value=result.dataUrl}catch(e){handle(e)}}
function handle(e:unknown){error.value=e instanceof ApiRequestError&&e.status===409?'设置已被其他设备修改，请刷新后重试':e instanceof Error?e.message:'操作失败'}
onMounted(load);
</script>
<template><section class="business-page"><header class="business-hero"><div><p class="business-eyebrow">Local settings</p><h1>系统设置</h1><p>设置以 SQLite 为唯一运行时事实源，备份时会生成只读配置快照。</p></div><AppButton :loading="saving" @click="save">保存设置</AppButton></header><AppErrorState v-if="error" title="设置操作失败" :description="error" @retry="load"/><p v-if="message" class="business-conflict">{{message}}</p><p v-if="loading">正在读取设置…</p><template v-else-if="data"><div class="business-form app-card"><AppInput v-model="data.appName" label="应用名称"/><AppInput v-model="data.subtitle" label="副标题"/><AppInput v-model="data.userNickname" label="昵称"/><AppInput v-model="data.defaultPort as unknown as string" label="端口"/><AppInput v-model="data.defaultRepeatDays as unknown as string" label="推荐避免重复天数"/></div><div class="settings-grid"><section class="app-card"><h2>自动化偏好</h2><label><input v-model="data.autoBackupEnabled" type="checkbox"> 自动备份</label><label><input v-model="data.autoDeductInventory" type="checkbox"> 完成日记时启用库存扣减闭环</label></section><section class="app-card"><h2>本地 PIN</h2><p>仅接受 4–8 位数字。</p><AppInput v-model="pin" type="password" label="新 PIN"/><div class="business-card__actions"><AppButton variant="ghost" @click="savePin(false)">关闭 PIN</AppButton><AppButton @click="savePin(true)">启用 PIN</AppButton></div></section><section class="app-card"><h2>手机访问二维码</h2><p>二维码只编码当前局域网访问地址，不依赖外部服务。</p><AppButton variant="secondary" @click="makeQr">生成二维码</AppButton><img v-if="qr" :src="qr" alt="局域网访问二维码"></section><section class="app-card"><h2>食用者与偏好</h2><p>管理忌口、过敏与默认餐量。</p><RouterLink class="app-button app-button--secondary app-button--md" to="/diners">管理食用者</RouterLink></section><section class="app-card"><h2>最近删除</h2><p>在 30 天内恢复误删的业务数据。</p><RouterLink class="app-button app-button--secondary app-button--md" to="/settings/deleted-items">打开回收站</RouterLink></section></div></template></section></template>
<style scoped>.settings-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.settings-grid section{display:grid;align-content:start;gap:14px}.settings-grid h2,.settings-grid p{margin:0}.settings-grid label{display:flex;gap:10px}.settings-grid img{width:220px;max-width:100%;border-radius:16px}@media(max-width:700px){.settings-grid{grid-template-columns:1fr}}</style>
